apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-pv
  labels:
    nfs: grafana-storage
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  mountOptions:
    - nfsvers=3
  nfs:
    path: /media/pi/Elements/k8sNFS/grafana/
    server: 192.168.1.91